services:
  organograma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organograma
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      - ./dados.json:/app/dados.json
      - ./uploads:/app/uploads
    environment:
      - PORT=5000
      - FLASK_DEBUG=false
    restart: unless-stopped
